name: self
description: An interpreter for the Self programming language
version: 1.0.0
repository: https://github.com/sma/dart_self

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.7.1
